### ISSUE TITLE
Problème gradle

### ISSUE THREAD

**Issue by Chifouuu** [Bricklou/javafx-launcher#3]
Bonjour, j'ai un problème avec gradle quand j'essaye d'éxécuter; 
voici l'erreur
[https://code.litarvan.com/coweqir.applescript](url)
Merci d'avance
Bonne soirée

**Comment by Bricklou** [comment]
Hello, tu peux passer sur le discord ici, cela sera plus simple pour t'aider : https://discord.gg/SAy4bVQgHD
